apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: int
spec:
  resources:
    cpu: "2"
    memory: "1G"
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 32Mi
---
apiVersion: k8spin.cloud/v1
kind: Space
metadata:
  namespace: org-example-tenant-crm
  name: pro
spec:
  resources:
    cpu: "3"
    memory: "2G"
  containers:
    defaults:
      resources:
        cpu: 10m
        memory: 32Mi