apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.k8spin.cloud
spec:
  scope: Namespaced
  group: k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
          - spec
          properties:
            spec:
              type: object
              required:
              - resources
              properties:
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      users:
                        type: array
                        items:
                          type: string
                    required:
                      - name
                resources:
                  type: object
                  required:
                  - cpu
                  - memory
                  properties:
                    cpu:
                      type: string
                    memory: 
                      type: string
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
    shortNames:
      - tens
      - ten