apiVersion: v1
kind: Service
metadata:
  name: k8spin-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "k8spin-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    application: k8spin-webhook
